[window]
decorations = "None"

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }
size = 14

[colors.normal]
black = "#000000"
red = "#FA6675"
green = "#6AAB73"
yellow = "#D5B778"
blue = "#56A8F5"
magenta = "#C77DBB"
cyan = "#299999"
white = "#eeeeee"

[colors.bright]
black = "#4f4f4f"
red = "#ff4d4b"
green = "#49cf22"
yellow = "#ffe365"
blue = "#5aa0ff"
magenta = "#e55ce5"
cyan = "#33bfbf"
white = "#ffffff"

[colors.primary]
foreground = "#e2eaf2"
background = "#000000"

[colors]
cursor = { cursor = "#e2eaf2" }

[keyboard]
bindings = [
  { key = "Up", mods = "Shift", action = "IncreaseFontSize" },
  { key = "Down", mods = "Shift", action = "DecreaseFontSize" },
]
