gui:
  showRandomTip: false
  splitDiff: auto
disableStartupPopups: true
keybinding:
  universal:
    prevBlock: '<c-k>'
    nextBlock: '<c-j>'
os:
  editPreset: 'nvim-remote'
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
