name: Build and Push Fedora Dev Bootc Image

permissions:
  packages: write

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - bootc

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: bootc

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/fedora-dev-bootc:latest
        file: ./Containerfile
        build-args: |
            email=${{ secrets.EMAIL  }}
            user=chris
    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io

